spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 .sql 파일 실행
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://database-1.cymwmpm0yhqt.ap-northeast-2.rds.amazonaws.com:3306/${RDS_MYSQL_NAME}
    username: ${RDS_MYSQL_USERNAME}
    password: ${RDS_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
